name: CI

on: [push, pull_request]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build binary
      run: |
        docker build -f Dockerfile -t moonlight-wii-builder .
        docker run --rm -v ${PWD}:/project moonlight-wii-builder make dist
    - uses: actions/upload-artifact@v4
      with:
       name: moonlight-wii
       path: dist/*
